apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-170901021
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-170901021
    app.kubernetes.io/part-of: test-app-170901021
  name: go-170901021
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-170901021
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-170901021
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/vi41v4ud-tenant/test-app-170901021/go-170901021@sha256:351526894487066f6fbac536c9bf036e9e2c0f69c72251fc02510800fdb9dd13
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
